// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FreeHand",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "FreeHand",
            targets: ["AppModule"],
            bundleIdentifier: "com.kyoya.FreeHandSSC",
            teamIdentifier: "3X7LEN654Y",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .paper),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .utilities
        )
    ],
    dependencies: [
        .package(url: "https://github.com/buh/CompactSlider", .exact("1.1.6"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CompactSlider", package: "compactslider")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
